import { BadgeCheck, CalendarCheck, MapPin, Scan, Sparkles, Ticket, Users } from "lucide-react";

export const eventItems = [
  {
    title: "AI-Generated VIP Passes",
    meta: "4.9 (428 reviews)",
    description: "Our AI designs stunning, unique VIP passes for each attendee with built-in QR verification technology, ensuring authenticity and security. No more generic tickets. Each pass is a work of art, personalized to your event.",
    icon: <Ticket className="w-4 h-4 text-purple-500" />,
    status: "Most Popular",
    tags: ["AI Design", "Custom", "Secure"],
    colSpan: 2,
    gradient: "from-purple-600 to-indigo-600",
    hasPersistentHover: true,
  },
  {
    title: "Instant QR Check-in",
    meta: "98% faster",
    description: "Guests arrive and scan - instant verification with our proprietary QR technology. No more long lines.",
    icon: <Scan className="w-4 h-4 text-blue-500" />,
    status: "Featured",
    tags: ["Fast", "Contactless", "Real-time"],
    gradient: "from-blue-600 to-cyan-600",
  },
  {
    title: "Smart Guest Management",
    meta: "AI Powered",
    description: "Our system learns preferences to personalize each experience and predict attendance patterns.",
    icon: <Users className="w-4 h-4 text-emerald-500" />,
    tags: ["AI", "Analytics", "Tracking"],
    gradient: "from-emerald-600 to-teal-600",
  },
  {
    title: "Event Location Analytics",
    description: "Discover optimal venues based on attendee demographics and historical event success rates.",
    icon: <MapPin className="w-4 h-4 text-red-500" />,
    meta: "New Feature",
    tags: ["Geo", "Analytics"],
    gradient: "from-red-600 to-pink-600",
  },
  {
    title: "Auto Calendar Sync",
    meta: "Zero Setup",
    description: "All events automatically sync to guests' calendars with smart reminders and updates.",
    icon: <CalendarCheck className="w-4 h-4 text-amber-500" />,
    status: "Verified",
    tags: ["Sync", "Reminders"],
    gradient: "from-amber-600 to-orange-600",
    rowSpan: 2,
  },
  {
    title: "Premium Event Templates",
    meta: "100+ designs",
    description: "Professionally designed templates for every occasion, all customizable with your branding.",
    icon: <Sparkles className="w-4 h-4 text-yellow-500" />,
    tags: ["Templates", "Branding"],
    gradient: "from-yellow-600 to-amber-600",
  },
  {
    title: "Enterprise Security",
    meta: "Military Grade",
    description: "End-to-end encryption and fraud prevention for high-profile corporate and government events. Your data is safe with us. We use the latest security protocols to ensure your event data is protected at all times.",
    icon: <BadgeCheck className="w-4 h-4 text-green-500" />,
    status: "Secure",
    tags: ["Encryption", "Compliance"],
    colSpan: 2,
    gradient: "from-green-600 to-emerald-600",
    hasPersistentHover: true,
  },
];
